import { NextPage } from "next";
import Head from "next/head";

const Chat: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Whatsapp TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Chat Page</h1>
    </div>
  );
};

export default Chat;
